#!/bin/sh
# -*- coding: utf-8 -*-
#
# @name_enUS '' 
# @name_zhTW '安裝 Audacious'
# @desc_enUS ''
# @desc_zhTW 'Linux 下有數不清的好用音樂播放軟體，但是對於原 Windows 使用者來說，
#             介面較不習慣，再加上目前仍有大量 MP3，還在使用 Big5 中文編碼。
#             Audacious 在正確設定下，能夠處理大部份的編碼問題，所以仍然是推薦使用。'
# @category 'Entertain'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <bill3321 -AT- gmail.com>'
# @author '洪任諭(PCMan) <pcman.tw -AT- gmail.com>'
# @license 'GPL'
# @debian 
# @ubuntu 
# @platform 'i386 amd64'


apt-get -y --force-yes install audacious audacious-plugins-extra

if [ -e "$REAL_HOME/.config/audacious/config" ]; then
    sed -i -e "/chardet_detector/d" "$REAL_HOME/.config/audacious/config"
    sed -i -e '/chardet_fallback/d' "$REAL_HOME/.config/audacious/config"
    sed -i -e '/\[audacious\]/a\chardet_detector=Taiwanese' "$REAL_HOME/.config/audacious/config"
    sed -i -e '/\[audacious\]/a\chardet_fallback=big5' "$REAL_HOME/.config/audacious/config"
else
    sudo -u $REAL_USER mkdir -p "$REAL_HOME/.config/audacious/"
    sudo -u $REAL_USER cat > "$REAL_HOME/.config/audacious/config" << EOF 
[audacious]
chardet_detector=Taiwanese
chardet_fallback=big5 
EOF
fi
