#!/bin/sh
# Copyright (C) 2007 朱昱任 (Yuren Ju) <yurenju -AT- gmail.com>
# Modified by PCMan on 2007.10.07
# Released under GNU General Public License
# @name_enUS '' 
# @name_zhTW '安裝 Mplayer 媒體播放程式'
# @desc_enUS ''
# @desc_zhTW '號稱最強大的多媒體播放程式，連在古董級老舊機器上都可以順暢播放。
#             Lazybuntu 協助安裝 Mplayer 之餘，還會協助加入適合中文字幕的設定。'
# @category 'Entertain'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <bill3321 -AT- gmail.com>'
# @author '朱昱任 (Yuren Ju) <yurenju -AT- gmail.com>'
# @license 'GPL'
# @debian 
# @ubuntu 
# @platform 'i386 amd64'


apt-get install -y --force-yes mplayer
mplayer_cfg_file="/etc/mplayer/mplayer.conf"

# FIXME: This is not very good...
sed -e 's/^subcp/# &/g' -i "$mplayer_cfg_file"
sed -e 's/^subfont-text-scale/# &/g' -i "$mplayer_cfg_file"
sed -e 's/^fontconfig/# &/g' -i  "$mplayer_cfg_file"
sed -e 's/^font=/# &/g' -i "$mplayer_cfg_file"

echo "subcp=cp950 #字型編碼" >> "$mplayer_cfg_file"
echo "subfont-text-scale=3 #字型縮小一點" >> "$mplayer_cfg_file"
echo "fontconfig=yes #開啟 fontconfig 支援" >> "$mplayer_cfg_file"
echo "font='AR PL ZenKai Uni'" >> "$mplayer_cfg_file"
