#!/bin/bash
# -*- coding: utf-8 -*-
# Copyright (C) 2007 洪任諭 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>
# Copyright (C) 2008 林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>
# Last Modified: 29 Dec 2008
# Released under GNU General Public License
# Download and install realplayer for i686 and x86_64 ubuntu
# Please run as root.
# Remove older version realplayer

case "$ARCH_NAME" in
i686)
echo '移除系統上原本的 Real Player 套件...'
apt-get --force-yes -y remove --purge realplay

echo '下載並安裝 Real Player 11...'
scripts/download-install realplay 'http://forms.real.com/real/player/download.html?f=unix/RealPlayer11GOLD.deb'
;;
x86_64)
#FIXME:use
# http://www.real.com/realcom/R?href=http://forms.real.com/real/player/download.html?f=unix/RealPlayer11GOLD.bin
echo '移除系統上原本的 Real Player 套件...'
apt-get --force-yes -y remove --purge realplay
echo '安裝相依性套件...'
apt-get --force-yes -y install lib32asound2 ia32-libs util-Linux build-essential Linux-headers-$(uname -r)

mkdir -p temp/realplay
TOP_DIR=`pwd`
cd temp/realplay
echo '下載並安裝 Real Player 11...'
wget 'http://forms.real.com/real/player/download.html?f=unix/RealPlayer11GOLD.bin'
chmod a+x RealPlayer11GOLD.bin
echo -e "\n\n\n" > real_echo
echo `pwd`
`pwd`/RealPlayer11GOLD.bin < real_echo

cd "$TOP_DIR"
;;
*)
echo "Real Player 目前尚未支援 $ARCH_NAME 硬體架構，取消安裝。"
;;
esac
