#!/bin/bash
# -*- coding: utf-8 -*-
#
# @name_enUS '' 
# @name_zhTW '安裝 Deluge BT 下載軟體'
# @desc_enUS ''
# @desc_zhTW 'Linux 下相當好用的 BT 下載軟體，滿足你的 P2P 下載需求。'
# @category 'Networking'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <bill3321 -AT- gmail.com>'
# @author '洪任諭(PCMan) <pcman.tw -AT- gmail.com>'
# @license 'GPL'
# @debian ''
# @ubuntu ''
# @platform 'i386 AMD64'

#TOP_DIR=`pwd`
#
#if [ $DISTRIB_CODENAME == "feisty" ]; then
#    subvernum="1"
#else
#    subvernum="2"
#fi
#
#if [ $DISTRIB_CODENAME != "hardy" ]; then
#    $TOP_DIR/scripts/download-install deluge "http://download.deluge-torrent.org/index.php?dir=ubuntu/${DISTRIB_CODENAME}/0.5.5/&file=deluge-torrent_0.5.5-${subvernum}_i386.deb"
#else
    apt-get -y --force-yes install deluge-torrent
#fi
