#!/bin/sh
# -*- coding: utf-8 -*-
#
# @name_enUS '' 
# @name_zhTW '安裝 Firefox 的 Flash 外掛'
# @desc_enUS ''
# @desc_zhTW '讓 Firefox/Iceweasel 可以正常顯示 Flash 動畫'
# @category 'Networking'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <bill3321 -AT- gmail.com>'
# @author '洪任諭(PCMan) <pcman.tw -AT- gmail.com>'
# @license 'GPL'
# @debian ''
# @ubuntu ''
# @platform 'i386 AMD64'
# @child 'Multimedia/multimedia-repos'

echo "解除安裝系統原本安裝的 Flash 播放器"
apt-get -y --force-yes --purge remove mozilla-plugin-gnash swfdec-mozilla

echo "正在下載、安裝 Flash"
if [ "$DISTRIB_ID" = "Ubuntu" ]; then
    apt-get -y --force-yes install flashplugin-nonfree
elif [ "$DISTRIB_ID" = "Debian" ]; then
    ./multimedia-repos
    apt-get -y --force-yes install flashplayer-mozilla 
else
    echo "Lazyscripts don't support your distibution now"
fi


