#!/bin/bash
# -*- coding: utf-8 -*-
# Copyright (C) 2007 洪任諭 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>
# Copyright (C) 2008 林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>
# Last Modified: 25 Nov 2008
# Released under GNU General Public License
# Download and install swiftfox.
# Please run as root.

. scripts/add-apt-sources

add_swiftfox

CPU=`scripts/cpu-type.py`
echo "自動偵測這台電腦上的 CPU 架構：$CPU"
if [ -n "$CPU" ]; then
    apt-get -y --force-yes install "swiftfox-$CPU"
else
    echo '錯誤：Lazybuntu 無法辨識本機 CPU 種類，安裝 SwiftFox 失敗'
fi
