#!/bin/bash
# -*- coding: utf-8 -*-
# Copyright (C) 2008 林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>
# Last Modified: 2 Apr 2009
# Released under GNU General Public License
# Declare 2 functions for adding medibuntu and ubuntu tweak source
# Please run as root.

# @hide


function add_medibuntu() {
if [ -e /etc/apt/sources.list.d/medibuntu.list ];then
    CHECK_MEDIBUNTU=`grep '$DISTRO_CODENAME' /etc/apt/sources.list.d/medibuntu.list`
    if [ -z "$CHECK_MEDIBUNTU" ];then
        wget http://www.medibuntu.org/sources.list.d/`lsb_release -cs`.list --output-document=/etc/apt/sources.list.d/medibuntu.list
        apt-get -q update
        apt-get --yes -q --allow-unauthenticated install medibuntu-keyring
        apt-get -q update
    else
        echo "Medibuntu 套件庫已經存在"
    fi
else
        wget http://www.medibuntu.org/sources.list.d/`lsb_release -cs`.list --output-document=/etc/apt/sources.list.d/medibuntu.list
        apt-get -q update
        apt-get --yes -q --allow-unauthenticated install medibuntu-keyring
        apt-get -q update
fi

#HAS_MEDIBUNTU=`grep '^deb http://packages.medibuntu.org/' /etc/apt/sources.list`
#if [ -z "$HAS_MEDIBUNTU" ]; then
# FIXME: We should check the codename of ubuntu here: dapper, feisty or gutsy?
#    echo -e "#the source of Medibuntu (Lazyscripts 新增)\ndeb http://packages.medibuntu.org/ $DISTRO_CODENAME free non-free" | sudo tee -a /etc/apt/sources.list
#    wget -q http://packages.medibuntu.org/medibuntu-key.gpg -O- | sudo apt-key add - && sudo apt-get update
#else
#    echo 'Medibuntu 套件庫已經存在'
#fi
}
function add_debian_multimedia(){
HAS_DEBIAN_MULTIMEDIA=`grep '^deb http://www.debian-multimedia.org' /etc/apt/sources.list`
if [ -z "$HAS_DEBIAN_MULTIMEDIA" ]; then
    wget http://www.debian-multimedia.org/pool/main/d/debian-multimedia-keyring/debian-multimedia-keyring_2008.10.16_all.deb
    dpkg -i ./debian-multimedia-keyring_2008.10.16_all.deb
    apt-get update
else
    echo "Debian Multimedia 套件庫已經存在"
fi
}
function add_ubuntu_tweak() {
HAS_UBUNTU_TWEAK=`grep '^deb http://ppa.launchpad.net/tualatrix/ubuntu' /etc/apt/sources.list`
if [ -z "$HAS_UBUNTU_TWEAK" ]; then
    if [ "$DISTRO_CODENAME" = 'intrepid' ];then
        echo -e "\n#the source of Ubuntu Tweak (Lazyscripts 新增)\ndeb http://ppa.launchpad.net/tualatrix/ubuntu intrepid main \ndeb-src http://ppa.launchpad.net/tualatrix/ubuntu intrepid main" | sudo tee -a /etc/apt/sources.list
    else
        echo -e "\n#the source of Ubuntu Tweak (Lazyscripts 新增)\ndeb http://ppa.launchpad.net/tualatrix/ubuntu hardy main \ndeb-src http://ppa.launchpad.net/tualatrix/ubuntu hardy main" | sudo tee -a /etc/apt/sources.list
    fi  
    wget -q http://ppa.launchpad.net/tualatrix/??-key.gpg -O- | sudo apt-key add - 
    sudo apt-get update
else
   echo 'Ubuntu Tweak 套件庫已經存在'
fi
}

function add_ubuntu_fonts() {
 HAS_UBUNTU_FONTS=`grep '^deb http://ppa.launchpad.net/fonts/ubuntu' /etc/apt/sources.list`
  if [ -z "$HAS_UBUNTU_FONTS" ]; then
    if [ "$DISTRO_ID" = "Ubuntu" ]; then
      echo -e "\n#the source of Ubuntu Fonts (Lazyscripts 新增)\ndeb http://ppa.launchpad.net/fonts/ubuntu $DISTRO_CODENAME main \n" | sudo tee -a /etc/apt/sources.list
    elif [ "$DISTRO_ID" = "Debian" ]; then
      echo -e "\n#the source of Ubuntu Fonts (Lazyscripts 新增)\ndeb http://ppa.launchpad.net/fonts/ubuntu intrepid main \n" | sudo tee -a /etc/apt/sources.list
    fi
      sudo apt-get update
  else
      echo 'Ubuntu Fonts 套件庫已經存在'

 fi

}

function add_swiftfox() {
HAS_SWIFTFOX=`grep '^deb http://getswiftfox.com/builds/debian' /etc/apt/sources.list`
if [ -z "$HAS_SWIFTFOX" ]; then
  echo -e "#the source of swiftfox (Lazyscripts 新增)\ndeb http://getswiftfox.com/builds/debian unstable non-free" >> /etc/apt/sources.list
    sudo apt-get update
  else
    echo 'Swifrfox 套件庫已經存在'
fi
}

function add_winehq() {
HAS_WINEHQ=`grep '^deb http://wine.budgetdedicated.com/apt' /etc/apt/sources.list`
if [ -z "$HAS_WINEHQ" ]; then
# FIXME: We should check the codename of ubuntu here: dapper, feisty or gutsy?
    echo -e "#the source of WineHQ Apt  (Lazyscripts 新增)\ndeb http://wine.budgetdedicated.com/apt $DISTRO_CODENAME main" | sudo tee -a /etc/apt/sources.list
    wget -q http://wine.budgetdedicated.com/apt/387EE263.gpg -O- | sudo apt-key add - && sudo apt-get update
else
    echo 'WineHQ 套件庫已經存在'
fi
}

function add_playonlinux() {
case $DISTRO_ID in 
    "Ubuntu")
    HAS_PLAYONLINUX=`grep '^deb http://deb.mulx.net/' /etc/apt/sources.list`
    if [ -z "$HAS_PLAYONLINUX" ]; then
     
        
        echo -e "#the source of PlayOnLinux (Lazyscripts 新增)\ndeb http://deb.mulx.net/ $DISTRO_CODENAME main" | sudo tee -a /etc/apt/sources.list
        wget -q http://deb.mulx.net/pol.gpg -O- | sudo apt-key add - && sudo apt-get update
    else 
        echo 'PlayOnLinux 套件庫已經存在'
    fi
    ;;
    "Debian")
    HAS_PLAYONLINUX=`grep '^deb http://deb.mulx.net/' /etc/apt/sources.list`
    if [ -z "$HAS_PLAYONLINUX" ]; then
        echo -e "#the source of PlayOnLinux (Lazyscripts 新增)\ndeb http://deb.mulx.net/ $DISTRO_CODENAME main" | sudo tee -a /etc/apt/sources.list
        # echo -e "#the source of PlayOnLinux (Lazyscripts 新增)\ndeb http://apt.wxwidgets.org/ etch-wx main" | sudo tee -a /etc/apt/sources.list
        wget -q http://deb.mulx.net/pol.gpg -O- | sudo apt-key add - && sudo apt-get update
        # sudo apt-get update
    else
        echo 'PlayOnLinux 套件庫已經存在'
    fi
    ;;
    *)
    echo "Sorry, Lazyscripts not support $DISTRO_ID "
    ;;
esac

}


function add_wicd() {
 HAS_WICD=`grep '^deb http://apt.wicd.net' /etc/apt/sources.list`
  if [ -z "$HAS_WICD" ]; then
    if [ "$DISTRO_ID" = "Ubuntu" ]; then
      echo -e "\n#the source of Wicd (Lazyscripts 新增)\ndeb http://apt.wicd.net $DISTRO_CODENAME extras \n" | sudo tee -a /etc/apt/sources.list
  elif [ "$DISTRO_ID" = "Debian" ]; then
      echo -e "\n#the source of Wicd (Lazyscripts 新增)\ndeb http://apt.wicd.net $DISTRO_CODENAME extras \n" | sudo tee -a /etc/apt/sources.list
    fi
      wget -q http://apt.wicd.net/wicd.gpg -O- | sudo apt-key add -
      sudo apt-get update
  else
      echo 'Wicd 套件庫已經存在'

  fi

}


function add_virtualbox() {
 HAS_VIRTUALBOX=`grep '^deb http://download.virtualbox.org/virtualbox/debian' /etc/apt/sources.list`
  if [ -z "$HAS_VIRTUALBOX" ]; then
      if [ $DISTRO_CODENAME == "jaunty" ]; then
          echo -e "\n#the source of VirtualBox (Lazyscripts 新增)\ndeb http://download.virtualbox.org/virtualbox/debian intrepid non-free\n" | sudo tee -a /etc/apt/sources.list
      else
          echo -e "\n#the source of VirtualBox (Lazyscripts 新增)\ndeb http://download.virtualbox.org/virtualbox/debian $DISTRO_CODENAME non-free\n" | sudo tee -a /etc/apt/sources.list
      fi
	  wget -q http://download.virtualbox.org/virtualbox/debian/sun_vbox.asc -O- | sudo apt-key add -
      sudo apt-get update
  else
      echo 'VirtualBox 套件庫已經存在'
  fi
}


#END
