#!/bin/sh
# -*- coding: utf-8 -*-
# Copyright (C) 2007 洪任諭 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>
# Copyright (C) 2008 林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>
# Last Modified: 25 Nov 2008
# Released under GNU General Public License
# Download and install gnetedit for i686 and x86_64 ubuntu
# Please run as root.
# @name_enUS '' 
# @name_zhTW '安裝 GNetDict 線上辭典'
# @desc_enUS ''
# @desc_zhTW '台灣網友開發的軟體，執行時連線到網路辭典，將查到的內容傳回顯示。
#             程式本身不內建任何辭典資料，只會顯示線上查詢的內容。'
# @category 'Productivity'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>'
# @author '洪任諭 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>'
# @license 'GPL'
# @debian ''
# @ubuntu ''
# @platform 'i386'

case "$ARCH_NAME" in
i686)

mkdir -p temp/gnetdict

TOP_DIR=`pwd`

cd temp/gnetdict

echo '正在下載 GNetDict 網路辭典前端介面...'

$WGET 'http://of.openfoundry.org/download_path/gnetdict/0.2.5.1/gnetdict_0.2.5.1-1ubuntu1_i386.deb'
$WGET 'http://of.openfoundry.org/download_path/gnetdict/0.2.5.1/gnetdict-0.2.5.1.tar.bz2'

echo '正在安裝 GNetDict'
"$TOP_DIR/scripts/debinstall.py" *.deb

tar -xjf *.tar.bz2
cd gnetdict-*/

# create default scripts
sudo -u "$REAL_USER" mkdir -p "$REAL_HOME/.gnetdict"

# bug of gnetdict... svn files shouldn't be packaged
rm -rf 'scripts/.svn'

sudo -u "$REAL_USER" cp -r scripts "$REAL_HOME/.gnetdict"

# prevent bug of gnetdict 0.2.5 :-(
sudo -u "$REAL_USER" touch "$REAL_HOME/.gnetdict/config"

cd "$TOP_DIR"
;;
x86_64)
echo "抱歉，目前GNetDict尚未支援 $ARCH_NAME 硬體架構，取消安裝。"
;;
*)
echo "抱歉，目前GNetDict尚未支援 $ARCH_NAME 硬體架構，取消安裝。"
;;
esac
