#!/bin/sh
# Copyright (C) 2007 朱昱任 (Yuren Ju) <yurenju -AT- gmail.com>
# Copyright (C) 2007 洪任諭 (PCMan) <pcman.tw@gmail.com>
# Released under GNU General Public License
# @name_enUS '' 
# @name_zhTW '安裝 StarDict 星際譯王及其字典檔'
# @desc_enUS ''
# @desc_zhTW '對岸網友開發的翻譯軟體，功能類似 Windows 下的譯點通，強大好用。
#             特色是包含多種豐富的辭典資料庫，並且可以支援滑鼠選取文字自動查詢。
#             請注意：其中有些字典資料來路不明，有違法疑慮，使用者請自行斟酌。'
# @category 'Productivity'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <bill3321 -AT- gmail.com>'
# @author '洪任諭 (PCMan) <pcman.tw@gmail.com>'
# @author '朱昱任 (Yuren Ju) <yurenju -AT- gmail.com>'
# @license 'GPL'
# @debian ''
# @ubuntu ''
# @platform 'i386 AMD64'

download_url_prefix='http://nchc.dl.sourceforge.net/sourceforge/stardict/'
temp_dir='temp/stardict/'
dic_dir='/usr/share/stardict/dic/'

mkdir -p "$temp_dir"
apt-get --force-yes -y install stardict

dict_list=" \
    stardict-cdict-big5-2.4.2.tar.bz2 \
    stardict-oxford-big5-2.4.2.tar.bz2 \
    stardict-xdict-ec-big5-2.4.2.tar.bz2 \
    stardict-xdict-ce-big5-2.4.2.tar.bz2 \
    stardict-cedict-big5-2.4.2.tar.bz2 \
    stardict-langdao-ec-big5-2.4.2.tar.bz2 \
    stardict-langdao-ce-big5-2.4.2.tar.bz2"

for d in $dict_list
do
    $WGET --output-document="$temp_dir$d" "$download_url_prefix$d"
    tar jxf "$temp_dir$d" --directory="$dic_dir"
done
