#!/bin/sh
# -*- coding: utf-8 -*-
#
# @name_enUS '' 
# @name_zhTW '修正FAT32磁碟分割設定'
# @desc_enUS ''
# @desc_zhTW '/etc/fstab 是 Linux 的磁碟分割區設定檔，Ubuntu 預設建立的設定檔有些小問題，
#             可能導致一些 Windows FAT32 分割區的檔名異常，勾選這個選項會視情況幫你修正。'
# @category 'Customize'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>'
# @author '洪任諭(PCMan) <pcman.tw -AT- gmail.com>'
# @license 'GPL'
# @ubuntu
# @platform 'i386 amd64'

# Turn off fsck for vfat partitions
FOUND=`grep vfat /etc/fstab`
if [ -n "$FOUND" ]; then
	echo '找到 vfat 分割區，正在修正 fstab...'
	BAKFILE=/etc/fstab-`date +%F`.bak
	cp /etc/fstab "$BAKFILE"
	sed -r 's/^(.+vfat[[:space:]]+.*[[:space:]]+[[:digit:]]+[[:space:]]+)([[:digit:]]).*$/\10/g' "$BAKFILE" > /etc/fstab
	echo "修正完成，原本的 /etc/fstab 檔已經備份到 $BAKFILE"
else
	echo '你的 fstab 內沒有 vfat 分割區，不需修正'
fi

# TODO: charset fix for cdroms
