#!/bin/sh
# -*- coding: utf-8 -*-
# Fix some permission-related error of unknown cause (Bug: #31830)
#
# @name_enUS '' 
# @name_zhTW '修復權限問題'
# @desc_enUS ''
# @desc_zhTW 'Ubuntu底下有些權限問題，這個script可以將其修正(Bug: #31830)'
# @category 'Customize'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>'
# @author '朱昱任 (Yuren Ju) <yurenju -AT- gmail.com>'
# @license 'GPL'
# @ubuntu 
# @platform 'i386 amd64'
# @hide

# List all filenames started with '.'
FILES_TO_FIX=`find $REAL_HOME -maxdepth 1 -name ".*"`

# Change owner to $REAL_USER
chown -R $REAL_USER: $FILES_TO_FIX

