#!/bin/sh
# -*- coding: utf-8 -*-
# Source: http://www.gnome-look.org/content/show.php/nuoveXT+2?content=56625
#
# @name_enUS 'Install nuoveXT Desktop Theme' 
# @name_zhTW '安裝 nuoveXT 圖示佈景主題'
# @desc_enUS ''
# @desc_zhTW 'Ubuntu 預設的圖示還不難看，不過，nuoveXT 更好看。這個佈景主題長久以來，一直蟬聯 Gnome-Look 網站最高使用者評價。'
# @category 'Customize'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>'
# @author '洪任諭(PCMan) <pcman.tw -AT- gmail.com>'
# @license 'GPL'
# @debian
# @ubuntu
# @platform 'i386 amd64'

echo '正在下載並安裝 nuoveXT 2 圖示佈景主題...'
mkdir -p temp/nuovext
TOP_DIR=`pwd`
cd temp/nuovext

# Gnome
$WGET 'http://nuovext.pwsp.net/files/nuoveXT.2.2.tar.bz2'
# KDE
$WGET 'http://nuovext.pwsp.net/files/nuoveXT-2.2_KDE.tar.gz'

FILES=`dir *.tar.gz`
for theme in $FILES
    do
        tar -xzf "$theme" --directory='/usr/share/icons'
    done

FILES=`dir *.tar.bz2`
for theme in $FILES
    do
        tar -xjf "$theme" --directory='/usr/share/icons'
    done

# Firefox
# $WGET 'http://gnome-look.org/content/download.php?content=61516&id=1'
# FIXME: there should be better way to do this
# firefox -install-global-theme *.jar


echo '設定 Gnome 桌面使用 NeuvoXT 圖示...'
sudo -u $REAL_USER gconftool-2 -t string -s /desktop/gnome/interface/icon_theme 'nuoveXT.2.2'

cd "$TOP_DIR"
