#!/bin/bash
# -*- coding: utf-8 -*-
#
# @name_enUS 'Install AcidRip'
# @name_zhTW '安裝 AcidRip'
# @desc_enUS ''
# @desc_zhTW '當好用的 DVD Rip 製作工具，操作介面相當簡易，轉檔品質優良。
#             可將 DVD 影片轉成 avi 檔，同時可保存字幕(以 *.sub 和 *.idx 的格式)。'
# @category 'Multimedia '
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>'
# @author '洪任諭(PCMan) <pcman.tw -AT- gmail.com>'
# @license 'GPL'
# @debian 
# @ubuntu 
# @platform 'i386 amd64'

if [ "$DISTRIB_ID" == "Debian" ]; then
    scripts/multimedia-repos
fi

apt-get  -y --force-yes install acidrip
