#!/bin/bash
# -*- coding: utf-8 -*-
#
# @name_enUS '' 
# @name_zhTW '安裝 GStreamer 的各種影音解碼外掛'
# @desc_enUS ''
# @desc_zhTW 'GStreamer 是一個影音的程式庫，目前 Linux 上有不少多媒體軟體，需要依賴它才能運作
#             但 Ubuntu 官方，礙於某些潛在的可能法律問題，預設拿掉了許多常用的影音解碼器，導致
#             許多常見的影音格式無法被支援。選擇這個項目會幫你裝回這些常用的影音格式支援。'
# @warn_zhTW '這些影音支援，隨各地法規不同，有可能不完全合法，請使用者自行斟酌。'
# @category 'Multimedia'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <bill3321 -AT- gmail.com>'
# @author '洪任諭(PCMan) <pcman.tw -AT- gmail.com>'
# @license 'GPL'
# @debian ''
# @ubuntu ''
# @platform 'i386 AMD64'


PACKAGES="gstreamer0.10-plugins-ugly gstreamer0.10-plugins-bad"

if [ "$DISTRIB_ID" == "Ubuntu" ]; then
    PACKAGES="$PACKAGES gstreamer0.10-plugins-ugly-multiverse gstreamer0.10-pitfdll gstreamer0.10-plugins-bad-multiverse"
fi

sudo apt-get install -y --force-yes $PACKAGES

