#!/bin/sh
# -*- coding: utf-8 -*-
# Copyright (C) 2007 洪任諭 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>
# Copyright (C) 2007 朱昱任 (Yuren Ju) <yurenju -AT- gmail.com>
# Copyright (C) 2008 林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>
# Last Modified: 25 Nov 2008
# Released under GNU General Public License
# Download and install hinedo for i686 and x86_64 ubuntu
# Please run as root.

case "$ARCH_NAME" in
i686)
URL=`$WGET -O - 'http://of.openfoundry.org/projects/814/download' | \
        sed -n 's/^.*<a href="\(.*hinedo.*ubuntu.*i386.deb\)">.*$/\1/p' | sed '2,2d'`
if [ x"$DISTRIB_CODENAME" = x"gutsy" -o \
     x"$DISTRIB_CODENAME" = x"hardy" -o \
     x"$DISTRIB_CODENAME" = x"intrepid" ]; then
    scripts/download-install hinedo "$URL"
else
    echo "Hinedo 目前沒有給 $DISTRIB_CODENAME 使用的版本，取消安裝。"
fi
;;
x86_64)
echo "Hinedo 目前並不支援 $ARCH_NAME 硬體架構，取消安裝。"
;;
*)
echo "Hinedo 目前並不支援 $ARCH_NAME 硬體架構，取消安裝。"
;;
esac

