#!/bin/sh
# -*- coding: utf-8 -*-
# Copyright (C) 2007 洪任諭 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>
# Copyright (C) 2007 朱昱任 (Yuren Ju) <yurenju -AT- gmail.com>
# Copyright (C) 2008 林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>
# Last Modified: 30 Mar 2009
# Released under GNU General Public License
# Download and install hinedo for i686 and x86_64 ubuntu
# Please run as root.
#
# @name_enUS '' 
# @name_zhTW '安裝 Hinedo 網路廣播收聽程式'
# @desc_enUS ''
# @desc_zhTW '透過縮小在工作列的小圖示，叫出選單，輕鬆收聽 Hinet 提供的網路廣播。
#             不用看大量的網路廣告，更不用開龐大的網路瀏覽器，就能直接收聽。'
# @category 'Multimedia'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <bill3321 -AT- gmail.com>'
# @author '洪任諭(PCMan) <pcman.tw -AT- gmail.com>'
# @license 'GPL'
# @debian ''
# @ubuntu ''
# @platform 'i386'


case "$PLAT_NAME" in
i686)
URL=`$WGET -O - 'http://of.openfoundry.org/projects/814/download' | \
        sed -n 's/^.*<a href="\(.*hinedo.*ubuntu.*i386.deb\)">.*$/\1/p' | sed '2,2d'`
if [ x"$DISTRIB_CODENAME" = x"gutsy" -o \
     x"$DISTRIB_CODENAME" = x"hardy" -o \
     x"$DISTRIB_CODENAME" = x"intrepid" ]; then
    scripts/download-install hinedo "$URL"
else
    echo "Hinedo 目前沒有給 $DISTRIB_CODENAME 使用的版本，取消安裝。"
fi
;;
x86_64)
echo "Hinedo 目前並不支援 $PLAT_NAME 硬體架構，取消安裝。"
;;
*)
echo "Hinedo 目前並不支援 $PLAT_NAME 硬體架構，取消安裝。"
;;
esac

