#!/bin/bash
# -*- coding: utf-8 -*-
# Copyright (C) 2007 洪任諭 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>
# Copyright (C) 2008 林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>
# Last Modified: 29 Dec 2008
# Released under GNU General Public License
# Download and install w32codecs or w64codecs for i686 and x86_64 ubuntu
# Please run as root.
#
# @name_enUS '' 
# @name_zhTW '加入 Medibuntu 套件庫並安裝 Win32 Codecs(hide)'
# @desc_enUS ''
# @desc_zhTW 'Ubuntu 官方因為某些法規及專利問題，沒有支援許多常用的影音格式。
#             於是有人成立非官方的 Medibuntu 套件庫，提供多種影音 Codecs，一般使用者幾乎都會需要用到這個非官方套件庫，建議考慮安裝。'
# @warn_zhTW '因為各地專利及著作權法規的不同，此套件庫內的套件並非全部都保證可以合法使用，請使用者自行斟酌。'
# @category 'Multimedia'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <bill3321 -AT- gmail.com>'
# @author '洪任諭(PCMan) <pcman.tw -AT- gmail.com>'
# @license 'GPL'
# @debian ''
# @ubuntu ''
# @platform 'i386 AMD64'
# @child 'Common/add-apt-sources'
# @hide

. add-apt-sources

add_medibuntu

case "$PLAT_NAME" in
i386)
apt-get -y --force-yes install non-free-codecs w32codecs
;;
x86_64)
apt-get -y --force-yes install non-free-codecs w64codecs
;;
*)
echo "抱歉，Lazybuntu目前不支援 $PLAT_NAME 硬體架構。"
;;
esac

