#!/bin/bash
# -*- coding: utf-8 -*-
# Copyright (C) 2007 洪任諭 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>
# Copyright (C) 2008 林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <billy3321 -AT- gmail.com>
# Last Modified: 29 Dec 2008
# Released under GNU General Public License
# Download and install w32codecs or w64codecs for i686 and x86_64 ubuntu
# Please run as root.

. scripts/add-apt-sources

add_medibuntu

case "$ARCH_NAME" in
i686)
apt-get -y --force-yes install non-free-codecs w32codecs
;;
x86_64)
apt-get -y --force-yes install non-free-codecs w64codecs
;;
*)
echo "抱歉，Lazybuntu目前不支援 $ARCH_NAME 硬體架構。"
;;
esac

