#!/bin/bash
# -*- coding: utf-8 -*-
# Copyright (C) 2007 朱昱任 (Yuren Ju) <yurenju -AT- gmail.com>
# Add Medibuntu source through Common/add_repos.py
# Released under GNU General Public License
# @name_enUS '' 
# @name_zhTW '加入 Medibuntu 套件庫並安裝 Win32 Codecs'
# @desc_enUS ''
# @desc_zhTW 'Ubuntu 官方因為某些法規及專利問題，沒有支援許多常用的影音格式。
#             於是有人成立非官方的 Medibuntu 套件庫，提供多種影音 Codecs，一般使用者幾乎都會需要用到這個非官方套件庫，建議考慮安裝。'
# @warn_zhTW '因為各地專利及著作權法規的不同，此套件庫內的套件並非全部都保證可以合法使用，請使用者自行斟酌。'
# @category 'Multimedia'
# @maintaner '林哲瑋 Zhe-Wei Lin (billy3321,雨蒼) <bill3321 -AT- gmail.com>'
# @author '朱昱任 (Yuren Ju) <yurenju -AT- gmail.com>'
# @license 'GPL'
# @debian ''
# @ubuntu ''
# @platform 'i386 AMD64'
# @child 'Common/add_repos.py'

if [ "$DISTRO_ID" == "Debian" ]; then
    uri="http://ftp.tw.debian.org/debian-multimedia/"
    comps="main"
    extra_packages=""
elif [ "$DISTRO_ID" == "Ubuntu" ]; then
    uri="http://packages.medibuntu.org/"
    comps="free non-free"
    extra_packages="non-free-codecs"
fi

./add_repos.py "$uri" "$DISTRO_CODENAME" "$comps" "多媒體套件庫 (Lazyscripts 新增)"

case "$DISTRO_ID" in
    "Ubuntu")
    apt-get -q update
    apt-get --yes -q --allow-unauthenticated install medibuntu-keyring
    ;;
    "Debian")
    $WGET http://www.debian-multimedia.org/pool/main/d/debian-multimedia-keyring/debian-multimedia-keyring_2008.10.16_all.debian
    dpkg -i debian-multimedia-keyring_2008.10.16_all.deb
esac



apt-get update

case "$PLAT_NAME" in
i386)
    apt-get -y --force-yes install w32codecs $extra_packages
;;
x86_64)
    apt-get -y --force-yes install w64codecs $extra_packages
;;
*)
    echo "抱歉，Lazyscripts目前不支援 $PLAT_NAME 硬體架構。"
;;
esac
